#+OPTIONS: num:nil toc:nil reveal_title_slide:nil 
#+REVEAL_ROOT: assets/reveal.js/
#+REVEAL_TRANS: Fade
#+REVEAL_THEME: none
#+REVEAL_EXTRA_CSS: assets/styles.css
#+REVEAL_PLUGINS-deactivate: (highlight)
#+REVEAL_EXTRA_CSS: vendor/highlight/styles/solarized-light.css
#+REVEAL_EXTRA_JS: { src: 'vendor/highlight/highlight.pack.js', callback: function() { var allPre, i, j; allPre = document.getElementsByTagName("pre"); for (i = 0, j = allPre.length; i < j; i++) {hljs.highlightBlock(allPre[i]);} }, condition: function() {return true; } }
#+REVEAL_DEFAULT_SLIDE_BACKGROUND_SIZE: 1400px
#+REVEAL_HLEVEL: 1
#+TITLE: Intro to Theme Development
#+Author: Benjamin Turner
#     
# * Summary
#   Creating and working with WordPress themes is a great way to learn more about WordPress as well as make your site look and function exactly how you want.
# 
#   We'll go over what goes into making a WordPress theme, as well as concepts like "the loop," "actions and filters," and the "template hierarchy."
# 
#   By the end of the talk, you should have a good overview of WordPress themes, as well as places to go for further learning.
# 
* Intro to WordPress Theme Development

  - Benjamin Turner
  - [[https://passionsplay.com][https://passionsplay.com]]
  - [[https://github.com/bgturner]]


  - https://bgturner.github.io/pp-presentation-intro-to-theme-development/

* 
  - Query
  - The Loop
  - Hooks
  - Enqueueing Assets
  - Template Files
  - Template Hierarchy


  - [[https://developer.wordpress.org/themes/][WordPress Theme Development Handbook]]

* What's a WebPage?
** HTML
#+BEGIN_SRC html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
</head>
<body>
	<h1>Intro to WP Theme Dev</h1>
	<!-- more markup -->
</body>
</html>
#+END_SRC

** CSS
#+BEGIN_SRC css
body {
	background-color: #50c6db;
  color: white;
}
#+END_SRC

** JS
#+BEGIN_SRC javascript
$( document ).ready(function() {
    console.log( "ready!" );
});
#+END_SRC

** We know what a Webpage is.
#+BEGIN_QUOTE
If I go to this link I get the content I want.
#+END_QUOTE

* Query
** How we ask WordPress for content
   - We do this by accessing a URL in our browser

** =example.com/=
   :PROPERTIES:
   :CUSTOM_ID: request-homepage
   :END:

#+BEGIN_QUOTE
Me - Hey WordPress, give me the homepage for the site.
#+END_QUOTE
#+BEGIN_QUOTE
WP - Sure thing!
#+END_QUOTE

** =example.com/contact=
   :PROPERTIES:
   :CUSTOM_ID: request-contact
   :END:

#+BEGIN_QUOTE
Me - Hello WordPress! May I please have the contact page?
#+END_QUOTE
#+BEGIN_QUOTE
WP - Here you go!
#+END_QUOTE

** =example.com/category/wordpress-theming=
   :PROPERTIES:
   :CUSTOM_ID: request-category
   :END:

#+BEGIN_QUOTE
Me - Yo, WP! Can I have all of the posts in the "WordPress Theming" category?
#+END_QUOTE
#+BEGIN_QUOTE
WP - Here's all of them. As you wish!
#+END_QUOTE

** =example.com/foo-bar=
   :PROPERTIES:
   :CUSTOM_ID: request-404
   :END:

#+BEGIN_QUOTE
Me - Ok, ok. But do you have one with a slug of "foo-bar"?
#+END_QUOTE
#+BEGIN_QUOTE
WP - Hmmm. Nope. 404!
#+END_QUOTE

** Remember
   - The query is a *request* from the browser to the server
   - The theme tells the server what the *response* looks like

* Registering a theme with WordPress
** Required files for a WP theme

  #+BEGIN_SRC
└── pp-theme-name
  ├── style.css
  └── index.php
  #+END_SRC

** =style.css=
   - Describes the theme to WordPress
   - Allows WordPress to "Activate" the theme in the Admin

*** =style.css=
#+BEGIN_SRC css
/**
 * Theme Name: Intro to Theme Development
 * Theme URI: https://github.com/passionsplay/example-intro-to-theme-development
 * Author: Benjamin Turner
 * Author URI: https://passionsplay.com
 * Description: An example WordPress theme to accompany a WordCamp talk.
 * Version: 1.0
 * Text Domain: pp-theme-dev
 *
 * License: GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 * Tags: simple, example
 *
 * This theme, like WordPress, is licensed under the GPL.
 * Use it to make something cool, have fun, and share what you've learned with others.
 */
#+END_SRC

** =index.php=
   - Defines the markup used on the page
   - This is the catch-all template that will be used if a more specific template isn't found
*** =index.php=
#+BEGIN_SRC php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
</head>
<body>
	<h1>Intro to WP Theme Dev</h1>
	<!-- more markup -->
</body>
</html>
#+END_SRC

** 
  :PROPERTIES:
  :reveal_background: assets/images/theme-dev-backend-001.png
  :END:

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-001.png
   :END:

* The Loop
  - How WordPress displays the posts from a query

   
  - [[https://developer.wordpress.org/themes/basics/the-loop/][Developer Handbook - The Loop]]

** 
#+BEGIN_SRC php
<?php
if ( have_posts() ) {
	// Do something if posts in the Query
	while ( have_posts() ) {
		the_post();
		// Do something for each post in the Query
	}
} else {
	// Do something if no posts in the Query
}
?>
#+END_SRC

** 
#+BEGIN_SRC php
<?php if ( have_posts() ) : ?>
    <?php while ( have_posts() ) : the_post(); ?>

      <p>Slightly more HTML-y</p>

    <?php endwhile; ?>
<?php endif; ?>
#+END_SRC
** =index.php=
#+BEGIN_SRC php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
</head>
<body>
	<h1>Intro to WP Theme Dev</h1>
  <?php
  if ( have_posts() ) {
    while ( have_posts() ) {
      the_post();
    }
  } else {
  }
  ?>
</body>
</html>
#+END_SRC

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-001.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-backend-edit-post.png
   :END:

** Template Tags
  - =the_title()=
  - =the_permalink()=
  - =the_content()=
  - ... lots more ...


  - [[https://codex.wordpress.org/Template_Tags][WordPress Codex - Template Tags]]

** 
 #+BEGIN_SRC php
 <!DOCTYPE html>
 <html lang="en">
 <head>
	 <meta charset="UTF-8">
	 <title>Intro to WP Theme Dev</title>
 </head>
 <body>
	 <h1>Intro to WP Theme Dev</h1>
	 <?php
	 if ( have_posts() ) {
		 while ( have_posts() ) {
		 the_post(); ?>
		 <article>
			 <h2>
				 <a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
			 </h2>
			 <div>
				 <?php the_content(); ?>
			 </div>
		 </article>
		 <?php
		 }
	 }
	 ?>
 </body>
 </html>
 #+END_SRC

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-002.png
   :END:

** You might notice...
   - There's not a lot going on in the =head= of the page. 
   - What about SEO?
   - Where's our stylesheet? 
   - What about javascript files?

* Hooks: Actions and Filters
#+BEGIN_QUOTE
Allows /other/ code to "do stuff" at a certain place in the code
#+END_QUOTE

   - [[https://codex.wordpress.org/Plugin_API][Codex - Plugin API]]

** We need to tell WordPress /where/ in our templates it can /do/ stuff.
** 
   - =wp_head()=
   - =wp_footer()=


   - [[https://developer.wordpress.org/reference/functions/wp_head/][Developer - =wp_head()=]]
   - [[https://developer.wordpress.org/reference/functions/wp_footer/][Developer - =wp_footer()=]]

** 
#+BEGIN_SRC php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
	<?php wp_head(); ?>
</head>
<body>
	<h1>Intro to WP Theme Dev</h1>
	<?php

  // the loop

	wp_footer(); ?>
</body>
</html>
#+END_SRC

** 
    :PROPERTIES:
    :reveal_background: assets/images/theme-dev-frontend-003.png
    :END:

* Enqueueing Assets
** =functions.php=
   :PROPERTIES:
   :CUSTOM_ID: enqueue-assets-functions-php
   :END:

** 
  #+BEGIN_SRC
└── pp-theme-name
  ├── functions.php
  ├── style.css
  ├── index.php
  └── js/
    └── example.js
  #+END_SRC

** =functions.php=
#+BEGIN_SRC php
<?php
/**
 * Proper way to enqueue scripts and styles.
 */
function pp_theme_dev_scripts() {
    wp_enqueue_style( 'style-name', get_stylesheet_uri() );
    wp_enqueue_script( 'script-name', get_template_directory_uri() . '/js/example.js', array('jquery'), '1.0.0', true );
}
add_action( 'wp_enqueue_scripts', 'pp_theme_dev_scripts' );
#+END_SRC

   - [[https://developer.wordpress.org/reference/hooks/wp_enqueue_scripts][Developer Hook - =wp_enqueue_scripts=]]
   - [[https://developer.wordpress.org/reference/functions/wp_enqueue_style/][Developer Function - =wp_enqueue_style()=]]
   - [[https://developer.wordpress.org/reference/functions/wp_enqueue_script/][Developer Function - =wp_enqueue_script()=]]

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-004.png
   :END:

* Template Files
  - Define how a site looks
  - Made up of HTML, Template Tags, and PHP code


  - [[https://developer.wordpress.org/themes/basics/template-files/][Developer Handbook - Template Files]]

** =index.php=

** Template Partials

  - =get_header()= --> =header.php=
  - =get_footer()= --> =footer.php=

*** 
#+BEGIN_SRC php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
	<?php wp_head(); ?>
</head>
<body>
	<h1>Intro to WP Theme Dev</h1>
	<?php
	if ( have_posts() ) {
		while ( have_posts() ) {
		the_post(); ?>
		<article>
			<h2>
				<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
			</h2>
			<div>
				<?php the_content(); ?>
			</div>
		</article>
		<?php
		}
	}
	wp_footer(); ?>
</body>
</html>
#+END_SRC

*** 
=index.php=
#+BEGIN_SRC php
<?php get_header(); ?>
<h1>Intro to WP Theme Dev</h1>
<?php
if ( have_posts() ) {
	while ( have_posts() ) {
	the_post(); ?>
	<article>
		<h2>
			<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
		</h2>
		<div>
			<?php the_content(); ?>
		</div>
	</article>
	<?php
	}
}
get_footer();
#+END_SRC

*** 
=header.php=
#+BEGIN_SRC php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Intro to WP Theme Dev</title>
	<?php wp_head(); ?>
</head>
<body>
#+END_SRC

*** 
=footer.php=
#+BEGIN_SRC php
  <?php wp_footer(); ?>
</body>
</html>
#+END_SRC

*** 
    :PROPERTIES:
    :reveal_background: assets/images/theme-dev-frontend-004.png
    :END:

*** Not much of a change.
    - But we've gained flexibility.
    - One place to edit the code.

*** Other common partials
  - =get_sidebar()= --> =sidebar.php=
  - =get_search_form()= --> =searchform.php=
  - =get_template_part('content')= --> =content.php=


  - [[https://developer.wordpress.org/themes/basics/template-files/#template-partials][Developer - Template Partials]]

* Template Hierarchy
  - How WordPress determines which template to load


  - [[https://developer.wordpress.org/themes/basics/template-hierarchy/][Theme Handbook - Template Hierarchy]]

** Each request is a query
   - =example.com/=
   - =example.com/contact=
   - =example.com/category/wordpress-theming=
   - =example.com/foo-bar=
** 
#+BEGIN_QUOTE
   Sometimes we want to display things in different ways depending on the query.
#+END_QUOTE

** Example
   - On the homepage, we only want the title for each post.
   - On single blog posts, we want the post's meta information.

** Add Two Templates
  #+BEGIN_SRC
└── pp-theme-name
  ├── home.php
  ├── single.php
  ├── style.css
  ├── functions.php
  ├── header.php
  ├── footer.php
  ├── index.php
  └── js/
    └── example.js
  #+END_SRC

** =home.php=
#+BEGIN_SRC php
<?php get_header(); ?>
<h1>Intro to Theme Dev - Home</h1>
<?php
if ( have_posts() ) {
	while ( have_posts() ) {
	the_post(); ?>
	<article>
		<h2>
			<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
		</h2>
	</article>
	<?php
	}
}
get_footer();
#+END_SRC

** =single.php=
#+BEGIN_SRC php
<?php get_header(); ?>
<h1>Intro to WP Theme Dev</h1>
<?php
if ( have_posts() ) {
	while ( have_posts() ) {
	the_post(); ?>
	<article>
		<h2>
			<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
		</h2>
		<div class="postmeta">
			<p><?php the_author(); ?></p>
			<p><?php the_date(); ?></p>
		</div>
		<div>
			<?php the_content(); ?>
		</div>
	</article>
	<?php
	}
}
get_footer();
#+END_SRC

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-005.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: assets/images/theme-dev-frontend-006.png
   :END:

** 
   :PROPERTIES:
   :reveal_background: assets/images/wp-hierarchy.png
   :END:

** Example
   - We want special treatment for posts that have the category of "WordPress Themeing"
   - =http://example.com/category/wordpress-themeing=

** 
#+BEGIN_SRC 
└── pp-theme-name
  ├── category-wordpress-theming.php
  └── ...
#+END_SRC

